include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Enforce explicit return types
    - always_declare_return_types
    
    # Prefer package imports over relative
    - always_use_package_imports
    
    # Avoid print statements in production
    - avoid_print
    
    # Avoid unnecessary containers
    - avoid_unnecessary_containers
    
    # Performance - use const where possible
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    
    # Code quality
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    
    # Widget organization
    - sort_child_properties_last
    
    # Keys
    - use_key_in_widget_constructors
    
    # Naming
    - file_names
    
    # Line length (warning only, not error)
    - lines_longer_than_80_chars

analyzer:
  errors:
    # Treat line length as warning, not error
    lines_longer_than_80_chars: warning
    
    # Missing required parameters is an error
    missing_required_param: error
    
    # Missing return is an error
    missing_return: error
  
  exclude:
    # Exclude generated files from analysis
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/generated/**'
    - 'lib/generated/**'
  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

# Additional strict mode options
strong-mode:
  implicit-casts: false
  implicit-dynamic: false
