name: calendar_ai_flutter
description: Mobile app for Calendar AI with iOS-native feel and cross-platform support
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.1
  google_sign_in: ^6.2.2
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.3
  
  # UI Utilities
  cupertino_icons: ^1.0.8
  intl: ^0.20.1
  uuid: ^4.5.1
  flutter_dotenv: ^5.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - .env
    - assets/images/
    - assets/icons/
  
  # Fonts (Optional - using system fonts for native feel)
  # fonts:
  #   - family: SFProText
  #     fonts:
  #       - asset: fonts/SF-Pro-Text-Regular.otf
